/**
 * ParentPortal.tsx
 * Public, no-login parent view.
 * URL: /parent-portal?token=<uuid>
 *
 * The token is generated by the owner/principal in AIPredictorPage
 * and stored in Firestore parent_tokens/{token} with pre-computed
 * student data snapshot (30-day expiry).
 *
 * Firestore rules must allow:
 *   match /parent_tokens/{token} { allow read: if true; }
 *
 * Indian market note: Parents can't use dashboards. This is a
 * simple, mobile-first, no-login link they can open on WhatsApp.
 */
import { useState, useEffect } from "react";
import { useSearchParams } from "react-router-dom";
import { db } from "@/lib/firebase";
import {
  collection, query, where, getDocs, limit,
} from "firebase/firestore";
import {
  GraduationCap, TrendingUp, TrendingDown, AlertTriangle,
  CheckCircle2, Clock, IndianRupee, BookOpen, Activity,
  ShieldAlert, Eye, Loader2, Minus,
} from "lucide-react";

// ── Types ─────────────────────────────────────────────────────────────────────
interface PortalData {
  studentName: string;
  branch: string;
  grade: string;
  attendance: number;
  avgScore: number;
  recentScores: number[];
  feeDefaulted: boolean;
  failProbability: number;
  riskLevel: "Safe" | "Watch" | "High" | "Critical";
  riskFactors: string[];
  recommendation: string;
  expiresAt: string;
}

// ── Helpers ───────────────────────────────────────────────────────────────────
function getRiskDisplay(level: PortalData["riskLevel"]) {
  switch (level) {
    case "Critical": return { label: "Urgent Attention Needed", color: "text-red-600",    bg: "bg-red-50",    border: "border-red-200",    icon: ShieldAlert };
    case "High":     return { label: "Needs Attention",         color: "text-orange-600", bg: "bg-orange-50", border: "border-orange-200", icon: AlertTriangle };
    case "Watch":    return { label: "Being Monitored",         color: "text-amber-600",  bg: "bg-amber-50",  border: "border-amber-200",  icon: Eye };
    default:         return { label: "Doing Well",              color: "text-emerald-600",bg: "bg-emerald-50",border: "border-emerald-200",icon: CheckCircle2 };
  }
}

function getAttColor(v: number) {
  if (v >= 85) return "#10b981";
  if (v >= 75) return "#f59e0b";
  return "#ef4444";
}

function getScoreColor(v: number) {
  if (v >= 75) return "#10b981";
  if (v >= 50) return "#f59e0b";
  return "#ef4444";
}

// Circular progress SVG
function CircleProgress({ value, color, size = 88 }: { value: number; color: string; size?: number }) {
  const r = (size - 12) / 2;
  const circ = 2 * Math.PI * r;
  const offset = circ - (value / 100) * circ;
  return (
    <svg width={size} height={size}>
      <circle cx={size/2} cy={size/2} r={r} fill="none" stroke="#e2e8f0" strokeWidth={6} />
      <circle
        cx={size/2} cy={size/2} r={r} fill="none"
        stroke={color} strokeWidth={6}
        strokeDasharray={circ} strokeDashoffset={offset}
        strokeLinecap="round"
        transform={`rotate(-90 ${size/2} ${size/2})`}
        style={{ transition: "stroke-dashoffset 1s ease" }}
      />
      <text x={size/2} y={size/2 + 5} textAnchor="middle" fontSize="18" fontWeight="800" fill={color}>
        {value}%
      </text>
    </svg>
  );
}

// ── Component ─────────────────────────────────────────────────────────────────
export default function ParentPortal() {
  const [params]  = useSearchParams();
  const token     = params.get("token") || "";

  const [data,    setData]    = useState<PortalData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error,   setError]   = useState("");

  useEffect(() => {
    if (!token) { setError("Invalid link — no token provided."); setLoading(false); return; }
    const load = async () => {
      try {
        // Query by token field
        const snap = await getDocs(
          query(collection(db, "parent_tokens"), where("token", "==", token), limit(1))
        );
        if (snap.empty) { setError("Link not found or has been revoked."); setLoading(false); return; }

        const doc  = snap.docs[0].data() as any;

        // Check expiry
        if (doc.expiresAt && new Date(doc.expiresAt) < new Date()) {
          setError("This link has expired. Please ask the school for a new link.");
          setLoading(false); return;
        }

        setData({
          studentName:     doc.studentName || "Your Child",
          branch:          doc.branch      || "—",
          grade:           doc.grade       || "—",
          attendance:      doc.attendance  ?? 0,
          avgScore:        doc.avgScore    ?? 0,
          recentScores:    doc.recentScores ?? [],
          feeDefaulted:    doc.feeDefaulted ?? false,
          failProbability: doc.failProbability ?? 0,
          riskLevel:       doc.riskLevel  || "Watch",
          riskFactors:     doc.riskFactors || [],
          recommendation:  doc.recommendation || "",
          expiresAt:       doc.expiresAt  || "",
        });
      } catch (e: any) {
        setError("Failed to load: " + e.message);
      }
      setLoading(false);
    };
    load();
  }, [token]);

  // ── Loading ───────────────────────────────────────────────────────────────
  if (loading) {
    return (
      <div className="min-h-screen bg-[#f8fafc] flex items-center justify-center">
        <div className="text-center space-y-3">
          <GraduationCap className="w-10 h-10 text-[#1e3a8a] mx-auto animate-pulse" />
          <p className="text-sm font-bold text-slate-500">Loading student report…</p>
        </div>
      </div>
    );
  }

  // ── Error ─────────────────────────────────────────────────────────────────
  if (error || !data) {
    return (
      <div className="min-h-screen bg-[#f8fafc] flex items-center justify-center px-4">
        <div className="bg-white rounded-[2rem] shadow-xl p-8 max-w-sm w-full text-center space-y-4">
          <div className="w-14 h-14 bg-red-50 rounded-full flex items-center justify-center mx-auto">
            <AlertTriangle className="w-7 h-7 text-red-500" />
          </div>
          <h2 className="text-lg font-black text-[#1e294b]">Link Error</h2>
          <p className="text-sm text-slate-500">{error || "Unknown error"}</p>
          <p className="text-xs text-slate-400">Please contact your school for a fresh report link.</p>
        </div>
      </div>
    );
  }

  const risk = getRiskDisplay(data.riskLevel);
  const RiskIcon = risk.icon;

  return (
    <div className="min-h-screen bg-[#f8fafc]">
      {/* ── Header ──────────────────────────────────────────────────────── */}
      <div className="bg-gradient-to-r from-[#1e3a8a] to-[#2563eb] text-white px-6 pt-10 pb-8">
        <p className="text-xs font-black uppercase tracking-[0.2em] text-blue-200 mb-3">Edullent</p>
        <h1 className="text-2xl font-black">Student Progress Report</h1>
        <p className="text-blue-100 text-sm mt-1 font-medium">{data.studentName}</p>
        <div className="mt-2 flex items-center gap-2">
          <span className="text-[11px] bg-white/10 text-blue-100 px-2 py-0.5 rounded-full font-bold">{data.grade}</span>
          <span className="text-[11px] bg-white/10 text-blue-100 px-2 py-0.5 rounded-full font-bold">{data.branch}</span>
        </div>
      </div>

      <div className="px-4 py-6 max-w-lg mx-auto space-y-4">

        {/* ── Risk Alert Banner ────────────────────────────────────────── */}
        <div className={`rounded-2xl border ${risk.border} ${risk.bg} p-4 flex items-start gap-3`}>
          <RiskIcon className={`w-5 h-5 ${risk.color} shrink-0 mt-0.5`} />
          <div>
            <p className={`font-black text-sm ${risk.color}`}>{risk.label}</p>
            <p className="text-xs text-slate-600 mt-0.5">{data.recommendation}</p>
          </div>
        </div>

        {/* ── Key Metrics ─────────────────────────────────────────────── */}
        <div className="grid grid-cols-2 gap-3">
          {/* Attendance */}
          <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-4 flex flex-col items-center gap-2">
            <CircleProgress value={data.attendance} color={getAttColor(data.attendance)} />
            <p className="text-xs font-black text-slate-500 uppercase tracking-wider">Attendance</p>
            {data.attendance < 75 && (
              <p className="text-[10px] text-red-500 font-bold text-center">Below 75% minimum</p>
            )}
          </div>

          {/* Average Score */}
          <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-4 flex flex-col items-center gap-2">
            <CircleProgress value={data.avgScore} color={getScoreColor(data.avgScore)} />
            <p className="text-xs font-black text-slate-500 uppercase tracking-wider">Avg Score</p>
            {data.avgScore < 50 && (
              <p className="text-[10px] text-red-500 font-bold text-center">Below passing mark</p>
            )}
          </div>
        </div>

        {/* ── Recent Test Scores ───────────────────────────────────────── */}
        {data.recentScores.length > 0 && (
          <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-5">
            <p className="text-xs font-black text-slate-500 uppercase tracking-widest mb-3 flex items-center gap-1.5">
              <BookOpen className="w-3.5 h-3.5" />
              Recent Test Scores
            </p>
            <div className="flex items-end gap-3">
              {[...data.recentScores].reverse().map((s, i) => {
                const maxH = 56;
                const barH = Math.max(8, Math.round((s / 100) * maxH));
                const col  = s >= 75 ? "#10b981" : s >= 50 ? "#f59e0b" : "#ef4444";
                return (
                  <div key={i} className="flex flex-col items-center gap-1 flex-1">
                    <span className="text-[10px] font-black" style={{ color: col }}>{s}%</span>
                    <div
                      className="w-full rounded-t-lg transition-all"
                      style={{ height: barH, backgroundColor: col, opacity: 0.85 }}
                    />
                    <span className="text-[9px] text-slate-400">#{i + 1}</span>
                  </div>
                );
              })}
            </div>
            {/* Trend indicator */}
            {data.recentScores.length >= 2 && (() => {
              const trend = data.recentScores[0] - data.recentScores[data.recentScores.length - 1];
              return (
                <div className={`mt-3 flex items-center gap-1 text-xs font-bold ${trend >= 0 ? "text-emerald-600" : "text-red-600"}`}>
                  {trend >= 0
                    ? <TrendingUp className="w-3.5 h-3.5" />
                    : <TrendingDown className="w-3.5 h-3.5" />
                  }
                  {trend >= 0
                    ? `Improved by ${trend} pts across last ${data.recentScores.length} tests`
                    : `Declined by ${Math.abs(trend)} pts — needs extra attention`
                  }
                </div>
              );
            })()}
          </div>
        )}

        {/* ── Fee Status ───────────────────────────────────────────────── */}
        <div className={`rounded-2xl border p-4 flex items-center gap-3 ${
          data.feeDefaulted
            ? "bg-amber-50 border-amber-200"
            : "bg-emerald-50 border-emerald-200"
        }`}>
          <IndianRupee className={`w-5 h-5 shrink-0 ${data.feeDefaulted ? "text-amber-600" : "text-emerald-600"}`} />
          <div>
            <p className={`text-sm font-black ${data.feeDefaulted ? "text-amber-700" : "text-emerald-700"}`}>
              {data.feeDefaulted ? "Fee Payment Pending" : "Fees Paid — Thank You!"}
            </p>
            {data.feeDefaulted && (
              <p className="text-xs text-amber-600 mt-0.5">Please contact the school office for fee payment.</p>
            )}
          </div>
        </div>

        {/* ── Risk Factors ─────────────────────────────────────────────── */}
        {data.riskFactors.length > 0 && data.riskLevel !== "Safe" && (
          <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-5">
            <p className="text-xs font-black text-slate-500 uppercase tracking-widest mb-3 flex items-center gap-1.5">
              <Activity className="w-3.5 h-3.5" />
              Areas Needing Attention
            </p>
            <ul className="space-y-2">
              {data.riskFactors.map((f, i) => (
                <li key={i} className="flex items-start gap-2 text-sm text-slate-600">
                  <span className="text-red-400 mt-0.5 shrink-0">•</span>
                  <span>{f}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* ── Footer ───────────────────────────────────────────────────── */}
        <div className="text-center pt-2 pb-6">
          <p className="text-[10px] text-slate-400 font-medium">
            Powered by <span className="font-black text-[#1e3a8a]">Edullent</span>
            {data.expiresAt && (
              <span> · Link valid until {new Date(data.expiresAt).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}</span>
            )}
          </p>
        </div>
      </div>
    </div>
  );
}
